function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 23-Nov-2022 17:59:12

% Create figure
figure1 = figure('WindowState','maximized');

% Create textbox
annotation(figure1,'textbox',[0.0228125 0.299121506682868 0.001 0.001],...
    'String',{'1'},...
    'FontSize',12,...
    'FontName','Palatino Linotype',...
    'FitBoxToText','off');

