%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ricca\OneDrive - Università degli Studi di Udine\MMC - PEMD - MMC\Tracce\TorqueSpeed.csv
%
% Auto-generated by MATLAB on 11-Jul-2022 10:46:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Times", "Omega_meRef", "Omega_meActual", "ControlTem", "Product15", "Gain3"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\ricca\OneDrive - Università degli Studi di Udine\MMC - PEMD - MMC\Tracce\TorqueSpeed.csv", opts);

%% Convert to output type
Times = tbl.Times;
Omega_meRef = tbl.Omega_meRef;
Omega_meActual = tbl.Omega_meActual;
ControlTem = tbl.ControlTem;
Product15 = tbl.Product15;
Gain3 = tbl.Gain3;

%% Clear temporary variables
clear opts tbl